/*
 * hardware/sha32_test.c
 *
 * Host-side test for sha256.h: verifies sha32() and hkdf_sha256() against
 * known-good vectors computed independently by Python's hashlib.
 *
 * Build and run (no hardware needed):
 *   gcc -O2 -Wall -o sha32_test hardware/sha32_test.c && ./sha32_test
 *   (or via: make -C hardware/soc_minimal/firmware test-sha32)
 *
 * Exit 0 on all-pass, exit 1 on any failure.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "sha256.h"

static int failures = 0;

static void check_sha32(const char *ogt, uint32_t expected)
{
    uint32_t got = sha32(ogt);
    if (got == expected) {
        printf("  PASS  sha32(%-44s) = 0x%08x\n", ogt, got);
    } else {
        printf("  FAIL  sha32(%-44s) = 0x%08x  expected 0x%08x\n",
               ogt, got, expected);
        failures++;
    }
}

static void check_hkdf(const char *label,
                       const uint8_t *ikm,  size_t ikm_len,
                       const uint8_t *salt, size_t salt_len,
                       const uint8_t *info, size_t info_len,
                       size_t         out_len,
                       const char    *expected_hex)
{
    uint8_t out[64];
    char    got_hex[129];
    size_t  i;

    if (out_len > sizeof(out)) {
        printf("  FAIL  %s: out_len too large\n", label);
        failures++;
        return;
    }

    hkdf_sha256(ikm, ikm_len, salt, salt_len, info, info_len, out, out_len);

    for (i = 0; i < out_len; i++)
        sprintf(got_hex + i * 2, "%02x", out[i]);
    got_hex[out_len * 2] = '\0';

    if (strcmp(got_hex, expected_hex) == 0) {
        printf("  PASS  hkdf %s\n", label);
    } else {
        printf("  FAIL  hkdf %s\n       got: %s\n  expected: %s\n",
               label, got_hex, expected_hex);
        failures++;
    }
}

int main(void)
{
    printf("=== sha32 vectors (9 Core OGTs + edge cases) ===\n");

    /* Generated by: python3 -c "import hashlib,struct; ogt='...';
       d=hashlib.sha256(ogt.encode()).digest();
       print(hex(struct.unpack('>I',d[:4])[0]))" */
    check_sha32("global.Core.BoardIdentity.boot",  0x68706247u);
    check_sha32("global.Core.Heartbeat.boot",       0x416d6848u);
    check_sha32("global.Core.FaultReporter.boot",  0x677d36a7u);
    check_sha32("global.Core.PerfReporter.boot",   0xeb2b7554u);
    check_sha32("global.Core.LumpLoader.boot",     0xd728290du);
    check_sha32("global.Core.TraceEmitter.boot",   0xa7ce2b32u);
    check_sha32("global.Core.NSInspector.boot",    0x404c79d5u);
    check_sha32("global.Core.MediaConsumer.boot",  0xe400ec35u);
    check_sha32("global.Core.BrowseClient.boot",   0xe7eed989u);

    /* Edge cases */
    check_sha32("",  0xe3b0c442u);   /* SHA256("") = e3b0c44298fc... */
    check_sha32("a", 0xca978112u);

    printf("\n=== RFC 5869 Appendix A.1 HKDF test vector ===\n");

    /* Test Case 1 from RFC 5869 Appendix A.1
     * Hash = SHA-256
     * IKM  = 0x0b0b0b...0b (22 octets)
     * salt = 0x000102...0c (13 octets)
     * info = 0xf0f1f2...f9 (10 octets)
     * L    = 42
     * OKM  = 3cb25f25...65 (42 octets) */
    static const uint8_t rfc_ikm[]  = {
        0x0b,0x0b,0x0b,0x0b,0x0b,0x0b,0x0b,0x0b,
        0x0b,0x0b,0x0b,0x0b,0x0b,0x0b,0x0b,0x0b,
        0x0b,0x0b,0x0b,0x0b,0x0b,0x0b
    };
    static const uint8_t rfc_salt[] = {
        0x00,0x01,0x02,0x03,0x04,0x05,0x06,
        0x07,0x08,0x09,0x0a,0x0b,0x0c
    };
    static const uint8_t rfc_info[] = {
        0xf0,0xf1,0xf2,0xf3,0xf4,0xf5,0xf6,0xf7,0xf8,0xf9
    };

    check_hkdf("RFC5869-A.1",
               rfc_ikm,  sizeof(rfc_ikm),
               rfc_salt, sizeof(rfc_salt),
               rfc_info, sizeof(rfc_info),
               42,
               "3cb25f25faacd57a90434f64d0362f2a"
               "2d2d0a90cf1a5a4c5db02d56ecc4c5bf"
               "34007208d5b887185865");

    printf("\n=== Summary ===\n");
    if (failures == 0) {
        printf("All tests PASSED.\n");
        return 0;
    } else {
        printf("%d test(s) FAILED.\n", failures);
        return 1;
    }
}
