## Vivado batch build script — QMTECH Wukong XC7A100T Church Machine LED Flash
## ============================================================================
## Usage (from the directory containing the extracted ZIP):
##
##   vivado -mode batch -source wukong_xc7a100t.tcl
##
## Prerequisites:
##   • Vivado 2020.x or later (WebPACK edition — free, covers Artix-7)
##   • church_wukong_xc7a100t.v   — Verilog netlist (generated by gen_rtlil.py)
##   • wukong_xc7a100t.xdc        — Pin / timing constraints (this directory)
##
## Output:
##   church_wukong_xc7a100t.bit   — Bitstream, copied here after write_bitstream
##
## Programming (after synthesis completes):
##   Option A — Vivado Hardware Manager (GUI):
##     open_hw_manager → connect_hw_server → open_hw_target
##     → Program Device → select church_wukong_xc7a100t.bit
##   Option B — Vivado Hardware Manager (batch):
##     See the Tcl snippet printed at the end of this script.
##   Option C — OpenOCD (Linux/macOS):
##     openocd -f interface/ftdi/digilent_jtag_smt2.cfg \
##             -f target/xilinx_a100t.cfg \
##             -c "adapter speed 10000; init; \
##                 pld load 0 church_wukong_xc7a100t.bit; exit"
## ============================================================================

set PART     "xc7a100tfgg676-1"
set TOP      "church_wukong_xc7a100t"
set PROJ_DIR "./vivado_wukong"
set JOBS     4

## ── Create Vivado project ──────────────────────────────────────────────────
create_project -force ${TOP} ${PROJ_DIR} -part ${PART}
set_property target_language Verilog [current_project]

## ── Add Verilog netlist ────────────────────────────────────────────────────
if {![file exists ${TOP}.v]} {
    error "Source not found: ${TOP}.v\nRun 'python -m hardware.gen_rtlil --wukong' first."
}
add_files -norecurse [list ${TOP}.v]
set_property file_type {Verilog} [get_files ${TOP}.v]

## ── Add constraints ────────────────────────────────────────────────────────
if {![file exists wukong_xc7a100t.xdc]} {
    error "Constraints not found: wukong_xc7a100t.xdc"
}
add_files -fileset constrs_1 -norecurse wukong_xc7a100t.xdc
set_property is_enabled true [get_files wukong_xc7a100t.xdc]

## ── Set top-level module ──────────────────────────────────────────────────
set_property top ${TOP} [current_fileset]
update_compile_order -fileset sources_1

## ── Synthesis ────────────────────────────────────────────────────────────
puts "\n═══ Synthesis starting (may take 5–15 min) ═══"
launch_runs synth_1 -jobs ${JOBS}
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] ne "100%"} {
    set log [glob -nocomplain ${PROJ_DIR}/${TOP}.runs/synth_1/*.log]
    error "Synthesis FAILED — check: $log"
}
puts "Synthesis complete."

## ── Implementation ───────────────────────────────────────────────────────
puts "\n═══ Implementation starting (may take 10–25 min) ═══"
launch_runs impl_1 -jobs ${JOBS}
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] ne "100%"} {
    set log [glob -nocomplain ${PROJ_DIR}/${TOP}.runs/impl_1/*.log]
    error "Implementation FAILED — check: $log"
}
puts "Implementation complete."

## Check for timing violations (warn only — don't fail at 50 MHz, should be clean)
set wns [get_property STATS.WNS [get_runs impl_1]]
if {$wns ne "" && $wns < 0} {
    puts "WARNING: Timing violation — WNS = ${wns} ns. Design may be unstable."
} else {
    puts "Timing clean (WNS = ${wns} ns)."
}

## ── Bitstream generation ─────────────────────────────────────────────────
puts "\n═══ Generating bitstream ═══"
launch_runs impl_1 -to_step write_bitstream -jobs ${JOBS}
wait_on_run impl_1

## Copy bitstream to working directory for easy access
set bit_src "${PROJ_DIR}/${TOP}.runs/impl_1/${TOP}.bit"
if {[file exists $bit_src]} {
    file copy -force $bit_src ${TOP}.bit
    puts "\n═══════════════════════════════════════════════════════════════════"
    puts " Bitstream ready: [pwd]/${TOP}.bit"
    puts "═══════════════════════════════════════════════════════════════════"
    puts ""
    puts " To program via Vivado Hardware Manager (Tcl console):"
    puts "   open_hw_manager"
    puts "   connect_hw_server -allow_non_jtag"
    puts "   open_hw_target"
    puts "   set_property PROGRAM.FILE {[pwd]/${TOP}.bit} \[lindex \[get_hw_devices\] 0\]"
    puts "   program_hw_devices \[lindex \[get_hw_devices\] 0\]"
    puts ""
    puts " Expected LED behaviour after programming:"
    puts "   D1 (J4):  solid ON during boot, then blinks ~1 Hz (NUC_PROGRAM running)"
    puts "   D2 (H6):  1 Hz heartbeat during boot, then OFF (lit = fault detected)"
    puts "═══════════════════════════════════════════════════════════════════"
} else {
    error "Bitstream not found at $bit_src — check implementation logs."
}
