#!/bin/bash
# run_efx_pnr.sh — Interface Designer + Place & Route for SoC+CM combined project
#
# Usage (from any directory):
#   bash ~/church-machine/hardware/soc_combined/run_efx_pnr.sh [PROJECT_XML]
#
# PROJECT_XML defaults to ~/church_project/SoC_minimal/church_soc.xml.
# EFX_PNR uses Efinity 2026.1 (2025.2 segfaults on efx_pnr).
#
# IMPORTANT NOTES:
#   - Interface Designer MUST run before efx_pnr to generate the LPF from
#     peri.xml; without it, IO pins (clk, uart_tx, LEDs) are placed randomly.
#   - efx_pnr requires explicit --family/--device flags; it does NOT auto-read
#     them from the project XML.  Omitting them causes an immediate SIGSEGV crash.
#   - Do NOT pass --use_vdb_file unless a VDB already exists from a prior run.
#   - --operating_conditions must match the XML timing_model ("C3" for Ti60F225).
#   - VDB is written by efx_map as <SOC_DIR>/top.vdb (named after the Verilog
#     top module "top"), NOT outflow/<circuit>.vdb. efx_run.py --flow map would
#     write outflow/<circuit>.vdb but efx_run.py requires PyQt6 (unavailable on
#     headless servers). We pass top.vdb directly to efx_pnr.

set -euo pipefail

EFINITY="${EFINITY_HOME:-$HOME/efinity/2026.1}"
EFX_PNR="$EFINITY/bin/efx_pnr"
EFX_RUN="$EFINITY/bin/efx_run"

# efx_pnr checks EFINITY_HOME at startup — must be exported
export EFINITY_HOME="$EFINITY"

# Do NOT source setup.sh — it calls `exit` in non-interactive shells and
# silently kills this script before it prints anything.  Add paths directly.
export PATH="$EFINITY/bin:${PATH:-}"
if [ -d "$EFINITY/lib" ]; then
    export LD_LIBRARY_PATH="$EFINITY/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi

# Default project: church_soc_cm.xml in the same directory as this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT="${1:-$SCRIPT_DIR/church_soc_cm.xml}"
SOC_DIR="$(dirname "$PROJECT")"
# Derive circuit name from the project XML filename (strip directory + .xml)
CIRCUIT="$(basename "$PROJECT" .xml)"
FAMILY="Titanium"
DEVICE="Ti60F225"
OPCOND="C3"

mkdir -p "$SOC_DIR/work_pnr" "$SOC_DIR/outflow"
# Headless servers throw KeyError for these vars if unset.
# EFINITY_USER_DIR_INI — user settings dir
# EFXPT_HOME           — Efinity platform tools home (defaults to EFINITY_HOME)
export EFINITY_USER_DIR_INI="${EFINITY_USER_DIR_INI:-$HOME/.efinity}"
export EFXPT_HOME="${EFXPT_HOME:-$EFINITY}"
mkdir -p "$EFINITY_USER_DIR_INI"
cd "$SOC_DIR"

# ----------------------------------------------------------------
# Step 0: Interface Designer
# Reads peri.xml → writes IO placement into the project database.
# On headless servers efx_run raises 'EFINITY_USER_DIR_INI' KeyError
# but still writes top.res.csv before exiting.  We capture that exit
# code and warn rather than abort so PnR can proceed with the CSV.
# ----------------------------------------------------------------
echo "==> Step 0/2: Interface Designer (IO placement from peri.xml) ..."
"$EFX_RUN" "$CIRCUIT" \
    --prj \
    --flow   interface \
    --family "$FAMILY" \
    -d       "$DEVICE" \
    2>&1 | tee "$SOC_DIR/outflow/interface.log" || \
    echo "    WARNING: Interface Designer exited non-zero (EFINITY_USER_DIR_INI quirk) — continuing."
# efx_run writes top.res.csv (named after Verilog top module, not circuit).
# Confirm the sync file exists before proceeding.
SYNC_FILE="$SOC_DIR/top.res.csv"
if [ ! -f "$SYNC_FILE" ]; then
    echo "ERROR: Interface Designer did not produce top.res.csv — cannot proceed."
    exit 1
fi
# efx_pnr's CSV parser treats backslash as a C escape prefix and crashes with
# "unknown escape sequence" when it sees Verilog escaped identifiers like \sig .
# Strip all backslashes from the sync file before passing it to efx_pnr.
sed -i 's/\\//g' "$SYNC_FILE"
echo "    Sync file: $SYNC_FILE (backslashes stripped)"
echo ""

# ----------------------------------------------------------------
# Step 1/2: Place & Route
# ----------------------------------------------------------------
echo "==> Step 1/2: Place & Route  ($PROJECT) ..."
echo "    EFX_PNR: $EFX_PNR"
echo "    Family:  $FAMILY / $DEVICE / $OPCOND"
echo ""

# --sync_file carries the IO placement constraints generated by Interface Designer.
# efx_run writes top.res.csv (named after top Verilog module) not outflow/<circuit>.interface.csv.
# --vdb_file points at top.vdb written by efx_map in the project root.
"$EFX_PNR" \
    --prj            "$PROJECT" \
    --circuit        "$CIRCUIT" \
    --family         "$FAMILY" \
    --device         "$DEVICE" \
    --operating_conditions "$OPCOND" \
    --pack --place --route \
    --vdb_file       "top.vdb" \
    --sync_file      "$SYNC_FILE" \
    --work_dir       "work_pnr" \
    --output_dir     "outflow" \
    2>&1 | tee "$SOC_DIR/work_pnr/pnr.log"

echo ""
echo "==> Place & Route complete. Output in $SOC_DIR/work_pnr/ and $SOC_DIR/outflow/"
echo "    Bitstream: $SOC_DIR/outflow/${CIRCUIT}.bit  (run run_efx_pgm.sh next)"
