#!/usr/bin/env bash
# scripts/build_ti60_bitstream.sh
#
# Single-command Ti60 F225 bitstream build pipeline.
# Runs: firmware compile → patch_sapphire_init.py → efx_map → efx_pnr → efx_pgm
# → copies output to bitstreams/church_ti60_f225.hex and writes a metadata sidecar.
#
# Usage (from repo root):
#   bash scripts/build_ti60_bitstream.sh
#   bash scripts/build_ti60_bitstream.sh --flash          # also flash + smoke-test
#
# Prerequisites:
#   Efinity 2025.2 (synthesis)   — $EFINITY_MAP_HOME  or ~/efinity/2025.2
#   Efinity 2026.1 (P&R + pgm)  — $EFINITY_HOME      or ~/efinity/2026.1
#   Efinity RISC-V IDE 2025.2   — toolchain at ~/efinity/efinity-riscv-ide-2025.2/toolchain/bin
#   openFPGALoader               — ~/oss-cad-suite/bin/openFPGALoader
#   pyserial                     — pip install pyserial (for smoke-test when --flash is used)
#
# Notes:
#   • script must be run from the repo root (not from hardware/soc_combined/).
#   • Efinity synthesis project lives in ~/church_project/SoC/ (the actual Efinity
#     project directory).  The repo hardware/soc_combined/ sources are the master;
#     they must already be in sync before running this script.
#   • sapphire.v and the symbol .bin files must be present in hardware/soc_combined/
#     (copied from Efinix IP and generated by the firmware build).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOC_DIR="${SOC_PROJECT_DIR:-$HOME/church_project/SoC}"
EFINITY_MAP="${EFINITY_MAP_HOME:-$HOME/efinity/2025.2}"
EFINITY="${EFINITY_HOME:-$HOME/efinity/2026.1}"
BITSTREAMS="$REPO_ROOT/bitstreams"
HW="$REPO_ROOT/hardware/soc_combined"
SCRIPTS="$REPO_ROOT/scripts"
DO_FLASH=0

for _arg in "$@"; do
    case "$_arg" in
        --flash) DO_FLASH=1 ;;
        *) echo "Unknown flag: $_arg" >&2; exit 1 ;;
    esac
done

# ── colour helpers ──────────────────────────────────────────────────────────
_ok()   { printf '\033[0;32m[OK]\033[0m  %s\n' "$*"; }
_info() { printf '\033[0;36m[..]\033[0m  %s\n' "$*"; }
_fail() { printf '\033[0;31m[FAIL]\033[0m %s\n' "$*" >&2; exit 1; }
_warn() { printf '\033[0;33m[WARN]\033[0m %s\n' "$*"; }

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Ti60 F225 Bitstream Build Pipeline"
echo "  Repo:    $REPO_ROOT"
echo "  SoC dir: $SOC_DIR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Step 0: Pre-flight checks ──────────────────────────────────────────────
_info "Step 0/7: Pre-flight checks"

if [ ! -x "$EFINITY_MAP/bin/efx_map" ]; then
    _fail "Efinity 2025.2 (efx_map) not found at $EFINITY_MAP/bin/efx_map
       Install Efinity 2025.2 or set EFINITY_MAP_HOME to override."
fi

if [ ! -x "$EFINITY/bin/efx_pnr" ]; then
    _fail "Efinity 2026.1 (efx_pnr) not found at $EFINITY/bin/efx_pnr
       Install Efinity 2026.1 or set EFINITY_HOME to override."
fi

if [ ! -d "$SOC_DIR" ]; then
    _fail "SoC project directory not found: $SOC_DIR
       Create it with: cp -r hardware/soc_combined ~/church_project/SoC
       or set SOC_PROJECT_DIR to override."
fi

SAPPHIRE_V="$HW/sapphire.v"
if [ ! -f "$SAPPHIRE_V" ]; then
    _fail "sapphire.v not found at $SAPPHIRE_V
       Copy it from: ~/efinity/2025.2/ipm/ip/efx_tsemac/fpga/Ti60F225_devkit/ip/sapphire/sapphire.v"
fi

_ok "Pre-flight checks passed"
echo ""

# ── Step 1: Build firmware ──────────────────────────────────────────────────
_info "Step 1/7: Build SoC firmware"
make -C "$HW/firmware" 2>&1 | tee /tmp/build_fw.log | tail -5
SYM0="$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol0.bin"
if [ ! -f "$SYM0" ]; then
    _fail "Firmware build failed: symbol0.bin not found. Check /tmp/build_fw.log"
fi
_ok "Firmware built — symbol files in $HW/"
echo ""

# ── Step 2: Patch sapphire.v ────────────────────────────────────────────────
_info "Step 2/7: Patch sapphire.v (embed firmware into BRAM init blocks)"
python3 "$SCRIPTS/patch_sapphire_init.py" \
    "$SAPPHIRE_V" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol0.bin" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol1.bin" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol2.bin" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol3.bin"
_ok "sapphire.v patched"
echo ""

# ── Step 3: Synthesis (EFX_MAP, Efinity 2025.2) ─────────────────────────────
_info "Step 3/7: Synthesis (efx_map — Efinity 2025.2, ~4 min)"
EFINITY_HOME="$EFINITY_MAP" bash "$HW/run_efx_map.sh" "$SOC_DIR/church_soc_cm.xml" 2>&1 | tee /tmp/build_map.log | tail -8

# Auto-detect circuit name from the .map.v file efx_map produced.
# Efinity 2025.2 writes it to outflow/ or work_syn/ — sometimes in a
# project-named subdirectory (e.g. work_syn/church_soc_cm/church_soc_cm.map.v).
# Use find -maxdepth 3 so subdirectory layouts are handled automatically.
MAP_V="$(find "$SOC_DIR/outflow" "$SOC_DIR/work_syn" -maxdepth 3 -name "*.map.v" 2>/dev/null | head -1)"
if [ -z "$MAP_V" ] || [ ! -f "$MAP_V" ]; then
    _warn "  Searched: $SOC_DIR/outflow/  and  $SOC_DIR/work_syn/"
    _warn "  All .map.v files anywhere under $SOC_DIR:"
    find "$SOC_DIR" -name "*.map.v" 2>/dev/null || true
    _fail "No *.map.v found after synthesis — synthesis may have failed. Check /tmp/build_map.log"
fi
CIRCUIT="$(basename "$MAP_V" .map.v)"
_ok "  Detected circuit name: $CIRCUIT (from $MAP_V)"

# Verify firmware baked in
_info "  Verifying BRAM INIT_0 lanes are non-zero..."

ALL_NONZERO=1
for SYM in 0 1 2 3; do
    LINENUM=$(grep -n "EFX_RAM10" "$MAP_V" | grep "ram_symbol${SYM}__D\\\$g1" | head -1 | cut -d: -f1)
    if [ -z "$LINENUM" ]; then
        _warn "  Could not locate ram_symbol${SYM} instance in map.v"
        ALL_NONZERO=0
        continue
    fi
    INIT0=$(sed -n "${LINENUM},$((LINENUM+4))p" "$MAP_V" | grep "INIT_0" | head -1)
    if echo "$INIT0" | grep -qE 'INIT_0.*"[0-9a-fA-F]*0{8}"'; then
        _warn "  INIT_0 for ram_symbol${SYM} looks zero — firmware may not be embedded!"
        ALL_NONZERO=0
    else
        _ok "  ram_symbol${SYM} INIT_0: $(echo "$INIT0" | grep -o '"[^"]*"' | head -1)"
    fi
done
if [ "$ALL_NONZERO" -eq 0 ]; then
    _fail "One or more BRAM lanes have zero INIT_0 — firmware not embedded.
       Re-run patch_sapphire_init.py and ensure optimize-zero-init-rom=0 in church_soc_cm.xml."
fi
_ok "All 4 BRAM INIT_0 lanes non-zero — firmware embedded"
echo ""

# ── Step 4: Place & Route (EFX_PNR, Efinity 2026.1) ────────────────────────
_info "Step 4/7: Place & Route (efx_pnr — Efinity 2026.1, ~5 min)"
bash "$HW/run_efx_pnr.sh" "$SOC_DIR/church_soc_cm.xml" 2>&1 | tee /tmp/build_pnr.log | tail -8
LBF="$SOC_DIR/work_pnr/${CIRCUIT}.lbf"
if [ ! -f "$LBF" ]; then
    _fail "P&R output not found: $LBF — P&R may have failed. Check /tmp/build_pnr.log"
fi
_ok "Place & Route complete"
echo ""

# ── Step 5: Generate SPI flash hex (efx_pgm) ────────────────────────────────
_info "Step 5/7: Generate SPI flash hex (efx_pgm, ~30 s)"
bash "$HW/run_efx_pgm.sh" "$SOC_DIR/church_soc_cm.xml" 2>&1 | tee /tmp/build_pgm.log | tail -5
HEX_SRC="$SOC_DIR/outflow/${CIRCUIT}.hex"
if [ ! -f "$HEX_SRC" ]; then
    _fail "Hex output not found: $HEX_SRC — efx_pgm may have failed. Check /tmp/build_pgm.log"
fi
_ok "Hex generated: $HEX_SRC ($(du -h "$HEX_SRC" | cut -f1))"
echo ""

# ── Step 6: Copy to bitstreams/ ─────────────────────────────────────────────
_info "Step 6/7: Copy output to $BITSTREAMS/"
mkdir -p "$BITSTREAMS"
cp "$HEX_SRC" "$BITSTREAMS/church_ti60_f225.hex"
if [ -f "$SOC_DIR/outflow/${CIRCUIT}.bit" ]; then
    cp "$SOC_DIR/outflow/${CIRCUIT}.bit" "$BITSTREAMS/church_ti60_f225.bit"
fi

# Detect firmware version from firmware.hex word at offset 0 or banner string
FW_VERSION="unknown"
FW_HEX="$HW/firmware/firmware.hex"
if [ -f "$FW_HEX" ]; then
    FW_VERSION="$(head -1 "$FW_HEX" 2>/dev/null || echo unknown)"
fi
# Prefer banner string extraction
FW_MAIN="$HW/firmware/main.c"
if [ -f "$FW_MAIN" ]; then
    FW_VER_STR="$(grep -o 'v[0-9]\+\.[0-9]\+' "$FW_MAIN" | head -1 || echo "")"
    if [ -n "$FW_VER_STR" ]; then
        FW_VERSION="$FW_VER_STR"
    fi
fi

HEX_SIZE=$(wc -c < "$BITSTREAMS/church_ti60_f225.hex")
BUILT_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

cat > "$BITSTREAMS/church_ti60_f225.json" <<ENDJSON
{
  "built_at": "$BUILT_AT",
  "firmware_version": "$FW_VERSION",
  "size_bytes": $HEX_SIZE
}
ENDJSON

_ok "Copied to $BITSTREAMS/church_ti60_f225.hex"
_ok "Metadata written to $BITSTREAMS/church_ti60_f225.json"
echo ""

# ── Step 7: Flash + smoke-test (optional, --flash flag) ─────────────────────
if [ "$DO_FLASH" -eq 1 ]; then
    _info "Step 7/7: Flash board with openFPGALoader"
    # Find openFPGALoader: prefer oss-cad-suite bundle, fall back to system install
    OFLPGM="${OSS_CAD_SUITE:-$HOME/oss-cad-suite}/bin/openFPGALoader"
    if [ ! -x "$OFLPGM" ]; then
        OFLPGM="$(which openFPGALoader 2>/dev/null || true)"
    fi
    if [ -z "$OFLPGM" ] || [ ! -x "$OFLPGM" ]; then
        _warn "openFPGALoader not found — skipping flash."
        _warn "Install with: sudo apt install openFPGALoader   or set OSS_CAD_SUITE."
    else
        sudo "$OFLPGM" -b titanium_ti60_f225_jtag -f "$BITSTREAMS/church_ti60_f225.hex"
        _ok "Flash complete"
        echo ""
        _info "  Waiting 5 s for board to boot..."
        sleep 5
        _info "  Running UART smoke-test..."
        python3 "$SCRIPTS/test_ti60_uart.py" --port=auto --baud=57600 --timeout=30 --verbose
    fi
else
    _info "Step 7/7: Flash skipped (pass --flash to flash + smoke-test automatically)"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  BUILD COMPLETE"
echo "  Output: $BITSTREAMS/church_ti60_f225.hex"
echo "  Meta:   $BITSTREAMS/church_ti60_f225.json"
echo ""
echo "  Good-build commit ritual:"
echo "    git add bitstreams/"
echo "    git commit -m \"bitstream: Ti60 $(date -u +%Y-%m-%d)\""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
