#!/usr/bin/env bash
# scripts/build_ti60_bitstream.sh
#
# Single-command Ti60 F225 bitstream build pipeline.
# Runs: firmware compile → patch_sapphire_init.py → efx_map → efx_pnr → efx_pgm
# → copies output to bitstreams/church_ti60_f225.hex and writes a metadata sidecar.
#
# Usage (from repo root):
#   bash scripts/build_ti60_bitstream.sh
#   bash scripts/build_ti60_bitstream.sh --flash          # also flash + smoke-test
#
# Prerequisites:
#   Efinity 2026.1 (synthesis + P&R + pgm) — $EFINITY_MAP_HOME / $EFINITY_HOME  or ~/efinity/2026.1
#   Efinity RISC-V IDE 2025.2   — toolchain at ~/efinity/efinity-riscv-ide-2025.2/toolchain/bin
#   openFPGALoader               — /usr/bin/openFPGALoader  (apt)  OR  ~/oss-cad-suite/bin/openFPGALoader
#   pyserial                     — pip install pyserial (for smoke-test when --flash is used)
#
# Notes:
#   • script must be run from the repo root (not from hardware/soc_combined/).
#   • Efinity synthesis project lives in ~/church_project/SoC/ (the actual Efinity
#     project directory).  The repo hardware/soc_combined/ sources are the master;
#     they must already be in sync before running this script.
#   • sapphire.v and the symbol .bin files must be present in hardware/soc_combined/
#     (copied from Efinix IP and generated by the firmware build).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOC_DIR="${SOC_PROJECT_DIR:-$HOME/church_project/SoC}"
EFINITY_MAP="${EFINITY_MAP_HOME:-$HOME/efinity/2026.1}"
EFINITY="${EFINITY_HOME:-$HOME/efinity/2026.1}"
BITSTREAMS="$REPO_ROOT/bitstreams"
HW="$REPO_ROOT/hardware/soc_combined"
SCRIPTS="$REPO_ROOT/scripts"
DO_FLASH=0

for _arg in "$@"; do
    case "$_arg" in
        --flash) DO_FLASH=1 ;;
        *) echo "Unknown flag: $_arg" >&2; exit 1 ;;
    esac
done

# ── colour helpers ──────────────────────────────────────────────────────────
_ok()   { printf '\033[0;32m[OK]\033[0m  %s\n' "$*"; }
_info() { printf '\033[0;36m[..]\033[0m  %s\n' "$*"; }
_fail() { printf '\033[0;31m[FAIL]\033[0m %s\n' "$*" >&2; exit 1; }
_warn() { printf '\033[0;33m[WARN]\033[0m %s\n' "$*"; }

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Ti60 F225 Bitstream Build Pipeline"
echo "  Repo:    $REPO_ROOT"
echo "  SoC dir: $SOC_DIR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Step 0: Pre-flight checks ──────────────────────────────────────────────
_info "Step 0/8: Pre-flight checks"

if [ ! -x "$EFINITY_MAP/bin/efx_map" ]; then
    _fail "Efinity 2026.1 (efx_map) not found at $EFINITY_MAP/bin/efx_map
       Install Efinity 2026.1 or set EFINITY_MAP_HOME to override."
fi

if [ ! -x "$EFINITY/bin/efx_pnr" ]; then
    _fail "Efinity 2026.1 (efx_pnr) not found at $EFINITY/bin/efx_pnr
       Install Efinity 2026.1 or set EFINITY_HOME to override."
fi

if [ ! -d "$SOC_DIR" ]; then
    _fail "SoC project directory not found: $SOC_DIR
       Create it with: cp -r hardware/soc_combined ~/church_project/SoC
       or set SOC_PROJECT_DIR to override."
fi

SAPPHIRE_V="$HW/sapphire.v"
if [ ! -f "$SAPPHIRE_V" ]; then
    _fail "sapphire.v not found at $SAPPHIRE_V
       Copy it from: ~/efinity/2025.2/ipm/ip/efx_tsemac/fpga/Ti60F225_devkit/ip/sapphire/sapphire.v"
fi

_ok "Pre-flight checks passed"
echo ""

# ── Step 1: Build firmware ──────────────────────────────────────────────────
_info "Step 1/8: Build SoC firmware"
make -C "$HW/firmware" 2>&1 | tee /tmp/build_fw.log | tail -5
SYM0="$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol0.bin"
if [ ! -f "$SYM0" ]; then
    _fail "Firmware build failed: symbol0.bin not found. Check /tmp/build_fw.log"
fi
_ok "Firmware built — symbol files in $HW/"
echo ""

# ── Step 2: Patch sapphire.v ────────────────────────────────────────────────
# patch_sapphire_init.py writes firmware BRAM init-data into the repo copy
# ($HW/sapphire.v).  After patching we MUST also copy it to $SOC_DIR because
# Efinity's church_soc_cm.xml references sapphire.v relative to the project
# directory (~/church_project/SoC/), NOT the repo directory.  Without this
# copy step synthesis silently re-uses the old version from $SOC_DIR and
# the flashed bitstream carries the previous firmware version.
_info "Step 2/8: Patch sapphire.v (embed firmware into BRAM init blocks)"
python3 "$SCRIPTS/patch_sapphire_init.py" \
    "$SAPPHIRE_V" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol0.bin" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol1.bin" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol2.bin" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol3.bin"
_ok "sapphire.v patched (repo copy: $SAPPHIRE_V)"
# Deploy patched sapphire.v to the Efinity project directory
cp "$SAPPHIRE_V" "$SOC_DIR/sapphire.v"
_ok "sapphire.v deployed to $SOC_DIR/sapphire.v"
echo ""

# ── Step 2.5: Copy CM Verilog and peri.xml to SoC project ───────────────────
# build/church_ti60_f225.v has 16K dmem[] entries but ~99% are zero.
# Zero assignments are stripped at commit time → only ~93 non-zero lines remain.
# This makes EFX_MAP synthesis 20–50× faster and prevents OOM hangs on
# resource-limited machines.  The stripped copy is kept in build/ (canonical);
# here we deploy it into the Efinity project directory before synthesis runs.
#
# church_soc_cm.peri.xml MUST also be deployed: top.v top-level ports (e.g.
# cm_uart_rx) must have matching GPIO entries in peri.xml or efx_map crashes
# with a bare STACK TRACE before printing any synthesis output.
_info "Step 2.5/8: Deploy CM Verilog to SoC project"
CM_V_SRC="$REPO_ROOT/build/church_ti60_f225.v"
CM_V_DST="$SOC_DIR/church_ti60_f225.v"
if [ ! -f "$CM_V_SRC" ]; then
    _fail "church_ti60_f225.v not found at $CM_V_SRC — regenerate with hardware/gen_verilog.py"
fi
cp "$CM_V_SRC" "$CM_V_DST"
NON_ZERO=$(grep -c "dmem\[" "$CM_V_DST" || true)
_ok "church_ti60_f225.v deployed ($NON_ZERO non-zero dmem[] lines)"

PERI_SRC="$HW/church_soc_cm.peri.xml"
PERI_DST="$SOC_DIR/church_soc_cm.peri.xml"
if [ -f "$PERI_SRC" ]; then
    cp "$PERI_SRC" "$PERI_DST"
    _ok "church_soc_cm.peri.xml deployed (IO pin definitions)"
else
    _warn "church_soc_cm.peri.xml not found at $PERI_SRC — skipping (existing SoC copy will be used)"
fi
echo ""

# ── Step 3: Synthesis (EFX_MAP, Efinity 2026.1) ─────────────────────────────
_info "Step 3/8: Synthesis (efx_map — Efinity 2026.1, ~4 min)"

# Efinity GUI re-injects infer_set_reset / infer_clk_enable into the local
# project XML whenever the project is opened.  These params crash efx_map
# (hard STACK TRACE exit) on 2025.2.  Strip them every time before synthesis.
sed -i \
    -e '/<efx:param name="infer_set_reset"/d' \
    -e '/<efx:param name="infer_clk_enable"/d' \
    "$SOC_DIR/church_soc_cm.xml"

EFINITY_HOME="$EFINITY_MAP" bash "$HW/run_efx_map.sh" "$SOC_DIR/church_soc_cm.xml" 2>&1 | tee /tmp/build_map.log | tail -8

# Derive circuit name from the project XML filename — same convention used by
# run_efx_pnr.sh and run_efx_pgm.sh.  This never requires map.v to exist.
CIRCUIT="$(basename "$SOC_DIR/church_soc_cm.xml" .xml)"
_ok "  Circuit: $CIRCUIT"

# Optional BRAM sanity-check via map.v — Efinity 2025.2 sometimes writes it to
# outflow/, sometimes work_syn/, sometimes a subdirectory.  If it cannot be
# found we warn and continue; P&R will fail with a clear error if synthesis
# actually produced bad output.
MAP_V="$(find "$SOC_DIR/outflow" "$SOC_DIR/work_syn" -maxdepth 3 -name "*.map.v" 2>/dev/null | head -1)"
if [ -z "$MAP_V" ] || [ ! -f "$MAP_V" ]; then
    _warn "  map.v not found under $SOC_DIR/outflow or work_syn — skipping BRAM check"
    _warn "  (This is normal for some Efinity 2025.2 project layouts.)"
    _warn "  P&R will proceed; it will fail if synthesis output is missing."
else
    _ok "  map.v: $MAP_V"
    _info "  Verifying BRAM INIT_0 lanes are non-zero..."
    ALL_NONZERO=1
    for SYM in 0 1 2 3; do
        LINENUM=$(grep -n "EFX_RAM10" "$MAP_V" | grep "ram_symbol${SYM}" | head -1 | cut -d: -f1 || true)
        if [ -z "$LINENUM" ]; then
            _warn "  Could not locate ram_symbol${SYM} instance in map.v (naming may differ in 2026.1)"
            ALL_NONZERO=0
            continue
        fi
        INIT0=$(sed -n "${LINENUM},$((LINENUM+4))p" "$MAP_V" | grep "INIT_0" | head -1 || true)
        if [ -z "$INIT0" ]; then
            _warn "  No INIT_0 param found near ram_symbol${SYM} — check map.v manually"
            ALL_NONZERO=0
        elif echo "$INIT0" | grep -qE 'INIT_0.*"[0-9a-fA-F]*0{8}"'; then
            _warn "  INIT_0 for ram_symbol${SYM} looks zero — firmware may not be embedded!"
            ALL_NONZERO=0
        else
            _ok "  ram_symbol${SYM} INIT_0: $(echo "$INIT0" | grep -o '"[^"]*"' | head -1 || true)"
        fi
    done
    if [ "$ALL_NONZERO" -eq 0 ]; then
        _warn "One or more BRAM lanes have zero INIT_0."
        _warn "If the board boots but firmware is silent, re-run patch_sapphire_init.py"
        _warn "and ensure optimize-zero-init-rom=0 in church_soc_cm.xml."
    else
        _ok "All 4 BRAM INIT_0 lanes non-zero — firmware embedded"
    fi
fi
echo ""

# ── Step 4: Place & Route (EFX_PNR, Efinity 2026.1) ────────────────────────
_info "Step 4/8: Place & Route (efx_pnr — Efinity 2026.1, ~5 min)"
bash "$HW/run_efx_pnr.sh" "$SOC_DIR/church_soc_cm.xml" 2>&1 | tee /tmp/build_pnr.log | tail -8
LBF="$SOC_DIR/work_pnr/${CIRCUIT}.lbf"
if [ ! -f "$LBF" ]; then
    _fail "P&R output not found: $LBF — P&R may have failed. Check /tmp/build_pnr.log"
fi
_ok "Place & Route complete"
echo ""

# ── Step 5: Generate SPI flash hex (efx_pgm) ────────────────────────────────
_info "Step 5/8: Generate SPI flash hex (efx_pgm, ~30 s)"
bash "$HW/run_efx_pgm.sh" "$SOC_DIR/church_soc_cm.xml" 2>&1 | tee /tmp/build_pgm.log | tail -5
HEX_SRC="$SOC_DIR/outflow/${CIRCUIT}.hex"
if [ ! -f "$HEX_SRC" ]; then
    _fail "Hex output not found: $HEX_SRC — efx_pgm may have failed. Check /tmp/build_pgm.log"
fi
_ok "Hex generated: $HEX_SRC ($(du -h "$HEX_SRC" | cut -f1))"
echo ""

# ── Step 6: Copy to bitstreams/ ─────────────────────────────────────────────
_info "Step 6/8: Copy output to $BITSTREAMS/"
mkdir -p "$BITSTREAMS"
cp "$HEX_SRC" "$BITSTREAMS/church_ti60_f225.hex"
if [ -f "$SOC_DIR/outflow/${CIRCUIT}.bit" ]; then
    cp "$SOC_DIR/outflow/${CIRCUIT}.bit" "$BITSTREAMS/church_ti60_f225.bit"
fi

# Detect firmware version from firmware.hex word at offset 0 or banner string
FW_VERSION="unknown"
FW_HEX="$HW/firmware/firmware.hex"
if [ -f "$FW_HEX" ]; then
    FW_VERSION="$(head -1 "$FW_HEX" 2>/dev/null || echo unknown)"
fi
# Prefer banner string extraction
FW_MAIN="$HW/firmware/main.c"
if [ -f "$FW_MAIN" ]; then
    FW_VER_STR="$(grep -o 'v[0-9]\+\.[0-9]\+' "$FW_MAIN" | head -1 || echo "")"
    if [ -n "$FW_VER_STR" ]; then
        FW_VERSION="$FW_VER_STR"
    fi
fi

HEX_SIZE=$(wc -c < "$BITSTREAMS/church_ti60_f225.hex")
BUILT_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

cat > "$BITSTREAMS/church_ti60_f225.json" <<ENDJSON
{
  "built_at": "$BUILT_AT",
  "firmware_version": "$FW_VERSION",
  "size_bytes": $HEX_SIZE
}
ENDJSON

_ok "Copied to $BITSTREAMS/church_ti60_f225.hex"
_ok "Metadata written to $BITSTREAMS/church_ti60_f225.json"
echo ""

# ── Step 7: Flash + smoke-test (optional, --flash flag) ─────────────────────
if [ "$DO_FLASH" -eq 1 ]; then
    _info "Step 7/8: Flash board with openFPGALoader"
    # Find openFPGALoader: prefer oss-cad-suite bundle, fall back to system install
    OFLPGM="${OSS_CAD_SUITE:-$HOME/oss-cad-suite}/bin/openFPGALoader"
    if [ ! -x "$OFLPGM" ]; then
        OFLPGM="$(which openFPGALoader 2>/dev/null || true)"
    fi
    if [ -z "$OFLPGM" ] || [ ! -x "$OFLPGM" ]; then
        _warn "openFPGALoader not found — skipping flash."
        _warn "Install with: sudo apt install openFPGALoader   or set OSS_CAD_SUITE."
    else
        sudo "$OFLPGM" -b titanium_ti60_f225_jtag -f "$BITSTREAMS/church_ti60_f225.hex"
        _ok "Flash complete"
        echo ""
        _info "  Waiting 5 s for board to boot..."
        sleep 5
        _info "  Running UART smoke-test..."
        python3 "$SCRIPTS/test_ti60_uart.py" --port=auto --baud=57600 --timeout=30 --verbose
    fi
else
    _info "Step 7/8: Flash skipped (pass --flash to flash + smoke-test automatically)"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  BUILD COMPLETE"
echo "  Output: $BITSTREAMS/church_ti60_f225.hex"
echo "  Meta:   $BITSTREAMS/church_ti60_f225.json"
echo ""
echo "  Good-build commit ritual:"
echo "    git add bitstreams/"
echo "    git commit -m \"bitstream: Ti60 $(date -u +%Y-%m-%d)\""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
