#!/usr/bin/env python3
"""
scripts/patch_mapv_init.py

Inject firmware bytes directly into the EFX_RAM10 INIT_ defparam statements
of the Sapphire system_ramA instances in church_soc_cm.map.v.

WHY THIS IS NEEDED
------------------
EFX_MAP on Efinix Titanium Ti60 ignores both $readmemb AND inline Verilog
initial block assignments when synthesising EFX_RAM10 BRAM primitives.
It creates the 64 system_ramA instances (when optimize-zero-init-rom=0) but
leaves all INIT_ parameters at zero.  The CPU therefore fetches 0x00000000 on
every instruction read and never executes the firmware.

This script reads the four byte-lane symbol files (same ones generated by
`make -C hardware/soc_combined/firmware`) and writes non-zero values directly
into the INIT_ defparam lines in map.v.  P&R then embeds those values in the
bitstream, and the firmware runs from reset.

USAGE
-----
Run from the repo root after synthesis:

    python3 scripts/patch_mapv_init.py \\
        hardware/soc_combined/outflow/church_soc_cm.map.v \\
        hardware/soc_combined/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol0.bin \\
        hardware/soc_combined/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol1.bin \\
        hardware/soc_combined/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol2.bin \\
        hardware/soc_combined/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol3.bin

The script edits map.v in-place and prints a summary.  Then run P&R as normal.

AFTER THIS SCRIPT
-----------------
    bash hardware/soc_combined/work_pnr/run_efx_pnr.sh
    ~/efinity/2025.2/bin/efx_pgm --project church_soc_cm --device Ti60F225 \\
        --family Titanium --active --bit_width 1 --spi_low_power_mode on \\
        --io_weak_pullup on --oscillator_clock_divider DIV8 --enable_roms smart
    sudo ~/oss-cad-suite/bin/openFPGALoader -b titanium_ti60_f225_jtag \\
        -f hardware/soc_combined/outflow/church_soc_cm.hex
"""

import sys
import re
import os

# ── EFX_RAM10 geometry ────────────────────────────────────────────────────────
# EFX_RAM10 = 10 240 bits total.
# With READ_WIDTH=8 / WRITE_WIDTH=8: 1 280 byte addresses per instance.
# Each INIT_ parameter is 256 bits = 32 bytes.
# 1 280 bytes / 32 bytes per INIT_ = 40 INIT_ parameters per instance
# (INIT_0 … INIT_27 in hexadecimal: 0x00 = INIT_0 … 0x27 = INIT_39).
BITS_PER_INIT   = 256          # each INIT_ is 256 bits
BYTES_PER_INIT  = BITS_PER_INIT // 8    # 32 bytes
INITS_PER_BRAM  = 40           # INIT_0 … INIT_27 (hex)
BYTES_PER_BRAM  = INITS_PER_BRAM * BYTES_PER_INIT   # 1 280 bytes per instance


def read_symbol_bin(path):
    """Return list of int from a $readmemb-format binary file (one 8-bit word per line)."""
    values = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("//") or line.startswith("@"):
                continue
            values.append(int(line, 2))
    return values


def bytes_to_init_hex(data_bytes):
    """
    Pack up to 32 bytes into a 256-bit Verilog hex literal (MSB first, as EFX_RAM10
    expects).  Pads with zeros if fewer than 32 bytes are supplied.
    """
    assert len(data_bytes) <= BYTES_PER_INIT
    padded = list(data_bytes) + [0] * (BYTES_PER_INIT - len(data_bytes))
    # EFX_RAM10 INIT_ stores address 0 at the LSB end of the 256-bit word,
    # so bytes are packed MSB-first in the hex string (highest address first).
    padded.reverse()
    value = 0
    for b in padded:
        value = (value << 8) | b
    return f"256'h{value:064X}"


def find_system_rama_instances(map_v_text):
    """
    Return list of instance names (as raw strings, with backslash escaping)
    for EFX_RAM10 instances that belong to system_ramA (contain 'ram_sym' or
    'system_ramA' in their hierarchical path, excluding u_cm).
    """
    # Match:  EFX_RAM10 \path/to/instance  (
    pattern = re.compile(
        r'EFX_RAM10\s+(\\[^\s(]+)',
        re.MULTILINE
    )
    instances = []
    for m in pattern.finditer(map_v_text):
        name = m.group(1)
        if "u_cm" in name:
            continue
        if "ram_sym" in name or "system_ramA" in name or "system_ram" in name.lower():
            instances.append(name)
    return instances


def build_firmware_flat(lanes, lane_idx):
    """
    Return a flat byte array for one byte lane.
    lane 0 = byte[7:0] of word, lane 1 = byte[15:8], etc.
    The symbol files already provide one byte per address (one byte lane).
    """
    return lanes[lane_idx]


def instance_to_lane(inst_name):
    """
    Heuristic: infer the byte-lane index from the instance name.
    Efinix names system_ramA byte-lane instances with 'symbol0' … 'symbol3'
    or '_D0' … '_D3' suffixes.  Fall back to None if ambiguous.
    """
    for i in range(4):
        if f"symbol{i}" in inst_name or f"_D{i}" in inst_name or f"ram{i}" in inst_name.lower():
            return i
    return None


def instance_to_chunk_index(inst_name):
    """
    Heuristic: infer which 1280-byte chunk of the lane this instance covers.
    EFX_MAP names cascaded BRAMs with a numeric suffix like _0, _1 … or
    uses hierarchical depth.  Returns None if it cannot be determined.
    """
    # Try trailing _N or $N
    m = re.search(r'[\$_](\d+)\s*$', inst_name)
    if m:
        return int(m.group(1))
    return None


def patch_instance_inits(map_v_text, inst_name, init_values):
    """
    Replace the INIT_N defparam lines for inst_name with the supplied values.
    init_values: list of up to INITS_PER_BRAM hex strings (256-bit each).
    Returns updated text and number of replacements made.
    """
    # Escape the instance name for regex (it contains backslash and slashes)
    escaped = re.escape(inst_name)
    replacements = 0
    for idx, hexval in enumerate(init_values):
        init_key = f"INIT_{idx}"
        pattern = re.compile(
            r'(defparam\s+' + escaped + r'\s+\.' + init_key + r'\s*=\s*)256\'h[0-9A-Fa-f]+;'
        )
        new_line = rf'\g<1>{hexval};'
        new_text, n = pattern.subn(new_line, map_v_text)
        if n > 0:
            map_v_text = new_text
            replacements += n
    return map_v_text, replacements


def main():
    if len(sys.argv) < 6:
        print(
            "Usage: patch_mapv_init.py map.v symbol0.bin symbol1.bin symbol2.bin symbol3.bin",
            file=sys.stderr,
        )
        sys.exit(1)

    map_v_path   = sys.argv[1]
    bin_paths    = sys.argv[2:6]

    # ── Load symbol files ──────────────────────────────────────────────────
    print("Loading symbol files …")
    lanes = []
    for i, path in enumerate(bin_paths):
        v = read_symbol_bin(path)
        nonzero = sum(1 for x in v if x)
        print(f"  symbol{i}: {len(v)} entries, {nonzero} non-zero  ({path})")
        lanes.append(v)

    # ── Load map.v ─────────────────────────────────────────────────────────
    print(f"\nLoading {map_v_path} …")
    with open(map_v_path, "r") as f:
        text = f.read()
    orig_len = len(text)

    # ── Find system_ramA EFX_RAM10 instances ──────────────────────────────
    instances = find_system_rama_instances(text)
    print(f"Found {len(instances)} system_ramA EFX_RAM10 instance(s).")

    if not instances:
        print(
            "\nERROR: No system_ramA EFX_RAM10 instances found in map.v.\n"
            "Ensure synthesis ran with optimize-zero-init-rom=0 and the\n"
            "patched sapphire.v (with inline initial block).",
            file=sys.stderr,
        )
        sys.exit(1)

    # Print first few for inspection
    for inst in instances[:5]:
        print(f"  {inst}")
    if len(instances) > 5:
        print(f"  … and {len(instances)-5} more")

    # ── For each instance, compute INIT_ values and patch ──────────────────
    total_replacements = 0
    total_nonzero_inits = 0

    for inst in instances:
        lane_idx = instance_to_lane(inst)
        chunk_idx = instance_to_chunk_index(inst)

        if lane_idx is None or chunk_idx is None:
            # Cannot determine mapping — skip with warning
            print(f"  WARNING: cannot determine lane/chunk for {inst} — skipping")
            continue

        lane_data = lanes[lane_idx]
        start_byte = chunk_idx * BYTES_PER_BRAM
        end_byte   = start_byte + BYTES_PER_BRAM

        # Extract the bytes for this instance (pad with 0 if beyond firmware)
        chunk = lane_data[start_byte:end_byte]
        chunk = chunk + [0] * (BYTES_PER_BRAM - len(chunk))

        # Split into INIT_ parameters (32 bytes each)
        init_hexvals = []
        for i in range(INITS_PER_BRAM):
            segment = chunk[i * BYTES_PER_INIT : (i + 1) * BYTES_PER_INIT]
            init_hexvals.append(bytes_to_init_hex(segment))

        nonzero_inits = sum(1 for h in init_hexvals if not all(c == '0' for c in h.split('h')[1]))
        total_nonzero_inits += nonzero_inits

        text, n = patch_instance_inits(text, inst, init_hexvals)
        total_replacements += n

    # ── Write patched map.v ────────────────────────────────────────────────
    with open(map_v_path, "w") as f:
        f.write(text)

    delta = len(text) - orig_len
    print(f"\nPatched {map_v_path}")
    print(f"  INIT_ defparams updated : {total_replacements}")
    print(f"  Instances with non-zero INIT_: {total_nonzero_inits > 0}")
    print(f"  File size delta: {delta:+,} chars")

    if total_replacements == 0:
        print(
            "\nWARNING: 0 defparam lines were updated.\n"
            "The instance names may use a different lane/chunk naming convention.\n"
            "Run with --debug to print all instance names, then adjust\n"
            "instance_to_lane() and instance_to_chunk_index() accordingly.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(
        "\nNext steps:\n"
        "  bash hardware/soc_combined/work_pnr/run_efx_pnr.sh\n"
        "  ~/efinity/2025.2/bin/efx_pgm --project church_soc_cm "
        "--device Ti60F225 --family Titanium --active --bit_width 1 "
        "--spi_low_power_mode on --io_weak_pullup on "
        "--oscillator_clock_divider DIV8 --enable_roms smart\n"
        "  sudo ~/oss-cad-suite/bin/openFPGALoader "
        "-b titanium_ti60_f225_jtag -f hardware/soc_combined/outflow/church_soc_cm.hex\n"
    )


if __name__ == "__main__":
    main()
